tildeio/helix

- Cargo.toml
Depending on * is considered bad practice, and crates.io won't even let you
upload a crate with it.
> depend on an actual libc version

- examples/README.md
Dearest Reviewer,
I want to check out the examples and get them running. I think this is
everything I had to do to get the membership benchmarks running. The odd
thing is that the benchmarks run fine but the rake irb command gives
this warning.
```
gcc -Wl,-force_load,target/release/libmembership.a --shared
-Wl,-undefined,dynamic_lookup -o lib/membership/native.bundle
Ignoring helix_runtime-0.5.0 because its extensions are not built.  Try:
gem pristine helix_runtime --version 0.5.0
```
I added the bundle install command to try and help it but it does not
seem to have helped. I could remove that step I think. Let me know.
Anyway, Thanks!
Becker
> Readme for examples

- crates/libcruby-sys/src/lib.rs
- ruby/ext/helix_runtime/native/helix_runtime.c
- ruby/ext/helix_runtime/native/helix_runtime.h
- src/coercions/string.rs
Hi @wycats, @chancancode!
I've been really excited about this project since last year when it was still called TurboRuby. I was really happy to see it come back as Helix at RailsConf this year!
I was playing around with the library and noticed that the only types that have `ToRuby` implementations so far are `()` and `bool`. Implementing the trait for `String` seemed straightforward, so I took a try at it.
I am definitely not an expert at Rust or MRI, so I'm not sure if this is the correct way to handle this. Please let me know!
> Implement ToRuby for String

- ruby/Rakefile
Enable different `dlltool` binary names as well as building both 32-bit and 64-bit `helix-runtime.lib`.
> compile *nix to windows using mingw

- README.md
Tiny fix. Make the input and output match capitalization. (Lowercasing "Rust" in the output would also fix this of course.)
> Fix capitalization in a README example.

- Cargo.toml
- crates/cstr-macro/Cargo.toml
- crates/cstr-macro/src/lib.rs
- src/class_definition.rs
- src/macros.rs
Unlike the previous Cstring::new approach, this approach doesn't
allocate. This will become important when we start using rb_raise
(which takes a C string but longjmps and therefore doesn't clean up
the memory).
(we got this implementation from @ubsan -- thanks!)
> Switch to using a new cstr!() macro

- README.md
This updates the README with the "getting started" information that's currently on the helix-website, but will be moved out. This details the steps needed to get started with the helix repository, and how to step through the examples.
> Update README With Getting Started Info

- Cargo.toml
Diff: https://github.com/dherman/cslice/compare/1522f67...e6ad
> Bump cslice crate: 0.2 -> 0.3.

- ruby/lib/helix_runtime.rb
- ruby/lib/helix_runtime/project.rb
> Fix var shadowing and ambiguous args in ruby warnings

- ruby/helix_runtime.gemspec
I was trying to find the repo from Rubygems, and realised that unlike most gems I've come across, it doesn't link to the GitHub repository. So, this change added all the metadata that seemed appropriate to the gem spec.
> Add metadata to gemspec

- src/lib.rs
- src/macros/coercions.rs
The previous code was relying on the accidental fact that only a single
impl of PartialEq<usize> existed. serde_json defines another impl of
PartialEq<usize>, which causes the constraint to be insufficient, which
results in a compile error when serde_json is added to a project with
Helix.
This commit forces the VALUE into a usize eagerly, avoiding this
inference issue.
Fixes #93
h/t @alyssais
Thanks to @nikomatsakis for helping me figure out the root cause.
> Fix compat with serde_json

- src/macros/init.rs
Asserting unwind safe is supposed to mean that we poison mutable object
involved in the panic (to prevent objects that were involved in panics
from triggering errors over and over again) and we should do that in the
future.
Fixes https://gist.github.com/citizen428/fd4fb386d6a78f09e217f1fe9d01834c
/cc @citizen428
> Allow any closure to be used with catch_panic

- ruby/lib/helix_runtime/build_task.rb
- ruby/lib/helix_runtime/parent_project.rb
- ruby/lib/helix_runtime/project.rb
Fix building when project name in HelixRuntime::BuildTask is different then the root directory name.
If the project name in Rake task and directory name do not match, running `rake build` fails with an error message like
```
native source doesn't exist, run `cargo_build` first; source=/Users/lautis/Git/rscsv-2/target/release/librscsv-2.dylib
```
This especially annoying if the build task is run during gem installation. In that case the directory name is `<gem-name>-<version>`.
> Use build task name as project name

- CHANGELOG.md
- Cargo.toml
- crates/libcruby-sys/Cargo.toml
- examples/calculator/Gemfile.lock
- examples/calculator/Rakefile
- examples/console/Gemfile.lock
- examples/console/Rakefile
- examples/duration/Gemfile.lock
- examples/duration/Rakefile
- examples/membership/Gemfile.lock
- examples/membership/Rakefile
- examples/text_transform/Gemfile.lock
- examples/text_transform/Rakefile
- examples/turbo_blank/Gemfile.lock
- examples/turbo_blank/Rakefile
- ruby/ext/helix_runtime/native/helix_runtime.c
- ruby/helix_runtime.gemspec
- ruby/lib/helix_runtime/build_task.rb
- ruby/lib/helix_runtime/cli/templates/helix_runtime.rake
- ruby/lib/helix_runtime/parent_project.rb
- ruby/lib/helix_runtime/project.rb
- ruby/lib/helix_runtime/version.rb
Since we already have the `Cargo.toml`, we don't actually need the user to pass the project name. Further more, the build task doesn't actually work correctly if you pass any name _other than_ what is in your `Cargo.toml` (as seen in #92).
Fixes #110.
Tested in helix-flipper.
> Deprecate passing project name to `BuildTask`

- .travis.yml
There is a bug in Cargo, where `.gitignore` will override the include
directive in `Cargo.toml`. Since the `.gitignore` included `.lib`, the
`helix-runtime-*.x86_64.lib` and `helix-runtime-*.i386.lib` weren't being
packaged.
> Fix missing .lib files when building libcruby-sys

- ruby/Rakefile
Apparently, `-m` still includes some 64 bit objects when running
dlltool. It leads to a linking error when compiling on 32-bit windows:
```
helix-runtime-0-6-3.i386.lib(dnekh.o) : fatal error LNK1112: module
machine type 'x64' conflicts with target machine type 'X86'
```
When analyzing the 32-bit lib file, you can see the 64-bit objects.
```
$ objdump -f helix-runtime-0-6-2.i386.lib
In archive helix-runtime-0-6-2.i386.lib:
dfrzt.o:     file format pe-x86-64
architecture: i386:x86-64, flags 0x00000038:
HAS_DEBUG, HAS_SYMS, HAS_LOCALS
start address 0x0000000000000000
dfrzh.o:     file format pe-x86-64
architecture: i386:x86-64, flags 0x00000039:
HAS_RELOC, HAS_DEBUG, HAS_SYMS, HAS_LOCALS
start address 0x0000000000000000
dfrzs00056.o:     file format pe-i386
architecture: i386, flags …
```
> Need to use the right dlltool for the respective arch

- src/macros/mod.rs
- src/macros/parser.rs
Unfortunately, we will lose the span for these errors.
(See rust-lang/rust#44535)
> Use `compile_errors!` to report parse errors

- examples/calculator/Gemfile.lock
- examples/console/Gemfile.lock
- examples/duration/Gemfile.lock
- examples/membership/Gemfile.lock
- examples/text_transform/Gemfile.lock
- examples/turbo_blank/Gemfile.lock
- ruby/helix_runtime.gemspec
- ruby/lib/helix_runtime/project.rb
The [`toml` gem](https://github.com/jm/toml) is kinda broken:
```shell
$ ruby -rtoml -e 'puts TOML.load("a = {}")'
Failed to match sequence (ALL_SPACE (TABLE / TABLE_ARRAY / KEY_VALUE / COMMENT_LINE){0, } ALL_SPACE) at line 1 char 1.
`- Don't know what to do with "a = {}\n" at line 1 char 1.
{}
```
Luckily, [`tomlrb`](https://github.com/fbernier/tomlrb) is not:
```shell
$ ruby -rtomlrb -e 'puts Tomlrb.parse("a = {}")'
{"a"=>{}}
```
This came to light when I was trying to implement Helix and got inscrutable parse errors because my `Cargo.toml` had an inline table in it.
> Use 'tomlrb' instead of 'toml' gem

- examples/calculator/spec/calculator_spec.rb
- examples/calculator/src/lib.rs
- src/coercions/bool.rs
- src/coercions/float.rs
- src/coercions/integers.rs
- src/coercions/mod.rs
- src/coercions/option.rs
- src/coercions/result.rs
- src/coercions/string.rs
- src/coercions/unit.rs
- src/lib.rs
- src/macros/coercions.rs
- src/macros/init.rs
- src/macros/mod.rs
This switches the `to_ruby` trait method to return a `Result`, which allows the coercion to fail.
The most obvious use case for this is to implement coercion for the `Result` type in Rust (included in this PR), but there could be other reasons why a coercion might fail. For example, if we were to implement a coercion between a Rust and Ruby regular expression, the coercion could fail if the Rust regular expression uses some Rust-specific features that are not supported by the Ruby regular expression implementation.
> Allow `to_ruby`  to fail

- ruby/lib/helix_runtime/project.rb
For project name with more then one '-' using `sub` will only replace
the first occurence. This cause `copy_native` to be failed due to
`File.exist?` check failed. Use `gsub` instead to fix.
> Fix incorrect native_lib name format bug

- crates/libcruby-sys/src/lib.rs
- examples/text_transform/spec/text_transform_spec.rb
- examples/text_transform/src/lib.rs
- src/coercions/mod.rs
- src/coercions/symbol.rs
- src/lib.rs
The main use case for symbols is to use them as a HashMap key. However, this introduces a GC problem – we cannot store Ruby values in the heap without properly marking/registering them, otherwise they might get GC'ed by Ruby unexpectedly. (In fact, this is already a problem if you have a `Vec<VALUE>`.)
I tried to avoid introducing additional problems by pinning down any symbols that goes thought the coercion protocol. This is probably overly aggressive, as it would cause any dynamic symbols (e.g. `String#to_sym`) to become un-GC-able. We can revisit this once we have a more general-purpose system to encode pinning semantics in the type system.
> Add Symbol coercion

- Cargo.toml
- examples/json_builder/Cargo.toml
- examples/json_builder/Gemfile
- examples/json_builder/Gemfile.lock
- examples/json_builder/Rakefile
- examples/json_builder/lib/json_builder.rb
- examples/json_builder/spec/json_builder_spec.rb
- examples/json_builder/spec/spec_helper.rb
- examples/json_builder/src/coercion.rs
- examples/json_builder/src/lib.rs
- src/macros/coercions.rs
- src/macros/parser.rs
Using the object (calling Rust methods from Ruby) after consuming would raise a RuntimeError.
Also fixes some parser bugs that previously allowed invalid syntax through in the arguments position.
> Allow consuming self in methods

- crates/libcruby-sys/src/lib.rs
This is already re-exported by the runtime, but was missing a Rust
binding.
> Expose `T_DATA` in libcruby

- crates/libcruby-sys/src/lib.rs
There's no real logical grouping to these additions, they just happen to
be functions I needed in my library which uses libcruby
> Expose a smattering of functions in libcruby

- crates/libcruby-sys/src/lib.rs
While we may be treating the representation of this type as opaque, I
think we can reasonably assume that it will never change to anything
that isn't `Sync`.
I think it may be worth considering making `VALUE` be `Sync` as well.
Even though it is effectively a pointer, it's a pointer to a *Ruby*
object, and therefore subject to the GVL.
> impl `Sync` for `ID`

- crates/libcruby-sys/src/lib.rs
- examples/console/spec/console_spec.rb
- ruby/ext/helix_runtime/native/helix_runtime.c
- ruby/ext/helix_runtime/native/helix_runtime.h
- ruby/spec/helix_runtime_spec.rb
- ruby/spec/support/dummy/ext/dummy/dummy.c
- src/coercions/string.rs
Previously, we blindly assume Ruby strings are UTF-8 and turn them into Rust Strings (which *are* assumed to be UTF-8). This is clearly unsafe so this commit adds some checks to cofirm that and generate type errors appropiately.
> Safer string coercions

- ruby/lib/helix_runtime/project.rb
I've cherry-picked this from #148 because this bugfix is necessary to use cargo workspaces with helix.
> Fix cargo workspaces
